Task/01 setup
VasylBiliak/fe-react-2024 pull request #1
Opened 2024-04-20 02:06 UTC by VasylBiliak

2024-04-21 04:49 UTC, VasylBiliak commented
- [ ]  Mentor is added to pr
- [ ]  AC copied to pr description
- [ ]  link to deployed version added to pr
- [ ]  About block (text and image) added to the main page
- [ ]  On the widths 390px and 1280px, the site layout corresponds to the design

2024-04-21 09:18 UTC, MZabolotnev requested changes
Pls check deployment - its failed

2024-04-21 21:22 UTC, MZabolotnev requested changes

2024-04-21 21:22 UTC, MZabolotnev commented on src/components/about/About.component.tsx
> +                    <div className={styles.description}>
It can be more semantic. Pls use section / article instead of div

2024-04-23 08:12 UTC, MZabolotnev requested changes
Paddings missed in both views ( mobile / desktop )
<img width="613" alt="image" src="https://github.com/VasylBiliak/fe-react-2024/assets/25617217/5beb32f8-7447-4db4-a4e2-50170a113f52">

2024-04-24 10:40 UTC, MZabolotnev requested changes
Still not good. Reason - picture width is hardcoded width: 330px;. You can try width: 100% instead. 
<img width="476" alt="image" src="https://github.com/VasylBiliak/fe-react-2024/assets/25617217/10aeea03-6bf3-4cc6-b728-d77316e89ade">

2024-04-26 14:22 UTC, MZabolotnev approved these changes

2024-04-26 18:22 UTC, merged