Task/06 routing
VasylBiliak/fe-react-2024 pull request #6
Opened 2024-06-10 06:05 UTC by VasylBiliak

Acceptance Criteria for 1

- [ ]  Mentor is added to pr
- [ ]  AC copied to pr description
- [ ]  Link to deployed version is added to pr
- [ ]  LayoutComponent with a static header and footer, and an Outlet for dynamic content, is added.
- [ ]  Two routes, AboutPage and ProductsPage, are added.
- [ ]  The AboutPage is set as the index route.
- [ ]  A route for invalid pages is added, displaying Page not found with a link to the AboutPage.
Acceptance Criteria for 1*

- [ ]  The layout for ProductPage is added according to the design.
- [ ]  An additional route for ProductPage with dynamic parameters :id is added.
- [ ]  An additional request getProduct is implemented, using the product's id.

2024-06-13 19:24 UTC, vladyslav-yermolin-moc commented
As @MZabolotnev is on vacation, @vadym-zinchenko-moc please review

2024-06-16 17:33 UTC, vadym-zinchenko-moc commented
where is link to deployed version?

2024-06-16 17:36 UTC, vadym-zinchenko-moc requested changes

2024-06-16 17:36 UTC, vadym-zinchenko-moc commented on src/main.tsx
> +        <BrowserRouter basename="/fe-react-2024">
try to change this. Use hash router, because now navigation isn't working for deployed version and I can't check your homework.

2024-06-18 12:21 UTC, vadym-zinchenko-moc requested changes
`http://localhost:5173/fe-react-2024/` - it's not deployed version. It's your local enviroment

2024-06-18 12:21 UTC, vadym-zinchenko-moc commented on src/interfaces/Component.ts
> +    PRODUCTS = '/product_list',
`PRODUCTS = 'product_list'` isn't working without `/`

2024-06-18 12:21 UTC, vadym-zinchenko-moc commented on src/pages/ProductPage/ProductPage.component.tsx
> +                            className={`${styles.secondary_image} ${item === imageTitle ? styles.active_image : ''}`}
you cab use `clsx` for this structure, it can be more readable

2024-06-18 12:21 UTC, vadym-zinchenko-moc commented on src/components/Menu/Menu.component.tsx
> +                    className={window.location.pathname === Component.ABOUT ? styles.list_link_active : styles.list_btn}
use hook for this. We have learn `useLocation` and don't use window

2024-06-19 07:02 UTC, vadym-zinchenko-moc approved these changes

2024-06-19 07:02 UTC, merged